export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
import { Providers } from "./components/Provider";
import "./globals.css";
// import "../i18n";
// import { useTranslation } from "react-i18next";
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="px-14">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
