import SessionWrapper from "@/components/SessionWrapper";
import { Providers } from "../components/Provider";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
import "./globals.css";

export default function RootLayout({ children }) {
    return (
        <SessionWrapper>
            <html lang="en">
                <head>
                    <link
                        rel="stylesheet"
                        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
                    />
                </head>

                <body>
                    <Providers>{children}</Providers>
                </body>
            </html>
        </SessionWrapper>
    );
}
